/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

exports.seed = function (knex) {
  return knex('movies').insert([
    {
      name: 'Decision to Leave',
      director: 'Park Chan-Wook',
      length: '138 min',
      language: 'Korean',
      image: 'https://pbs.twimg.com/media/FQTALZNUcAQjw3d.jpg:large',
      first_showdate_id: '0730',
      first_showtime: '4:30PM',
      second_showdate_id: '0805',
      second_showtime: '8:30PM',
    },
    {
      name: 'Boy From Heaven',
      director: 'Tarik Saleh',
      length: '126',
      language: 'Arabic',
      image:
        'https://pics.filmaffinity.com/Boy_from_Heaven-683653305-large.jpg',
      first_showdate_id: '0729',
      first_showtime: '11:30AM',
      second_showdate_id: '0802',
      second_showtime: '2:30PM',
    },
    {
      name: 'Close',
      director: 'Lukas Dhont',
      length: '105',
      language: 'Dutch and French',
      image:
        'https://m.media-amazon.com/images/M/MV5BMDI0NDYyOTUtOWUyOS00OTFjLWIzY2MtMDk1YjdkNWMzOTBkXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_.jpg',
      first_showdate_id: '0801',
      first_showtime: '2:30PM',
      second_showdate_id: '0805',
      second_showtime: '9:00PM',
    },
  ])
}

// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate_id:'',
//   first_showtime:'',
//   second_showdate_id:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
// {
//   name:'',
//   director:'',
//   length:'',
//   language:'',
//   image:'',
//   first_showdate:'',
//   first_showtime:'',
//   second_showdate:'',
//   second_showtime:'',
// },
